# This workflow will build and push the zdb docker image
name: Deploy zdb

on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Login to Docker
      run: |
        # new login with new container registry url and PAT
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Build docker image with Maven
      run: mvn -B compile jib:build -DskipTests
