# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: docker pull camunda/zeebe:8.0.4
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B verify
  auto-merge:
    name: Auto-merge dependabot PRs
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.repository == 'Zelldon/zdb' && github.actor == 'dependabot[bot]'
    permissions:
      checks: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - id: metadata
        name: Fetch dependency metadata
        uses: dependabot/fetch-metadata@v1.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - id: merge
        name: Merge PR
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GITHUB_TOKEN: "${{secrets.AUTO_MERGE_GITHUB_TOKEN}}"
